name: CI

on:
  push:
    branches: [master, refine_dev, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    uses: kumose/x-ci/.github/workflows/ci-template.yml@v1
    with:
      config-command: |
        cmake --preset=default -DKMCMAKE_BUILD_TEST=ON
      build-command: |
        cmake --build build -j$(nproc)
      test-command: |
        ctest --test-dir build --output-on-failure -j1
      skip-macos-x86: true
      skip-windows-arm64: true
      skip-linux-musl-arm64: true
